FROM bitnami/minideb

ENV MYSQL_DATABASE db
ENV MYSQL_USER db
ENV MYSQL_PASSWORD db
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_MAX_ALLOWED_PACKET 16m

RUN mkdir /docker-entrypoint-initdb.data
ADD files /

# Install mariadb non-interactive. The root password setup
# gets thrown away when we delete /var/lib/mysql below.
ENV DEBIAN_FRONTEND="noninteractive"
RUN echo "mariadb-server mysql-server/root_password password $MYSQL_ROOT_PASSWORD" | debconf-set-selections && \
echo "mariadb-server mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD" | debconf-set-selections

RUN apt-get -qq update && \
apt-get -qq install --no-install-recommends --no-install-suggests \
	software-properties-common \
	dirmngr \
	gnupg \
	vim \
	less \
	wget \
	sudo \
	telnet \
	procps && \
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8 && \
add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian stretch main' && \
apt-get -qq update && apt-get -qq install --no-install-recommends --no-install-suggests mariadb-server mariadb-client && \
apt-get -qq autoremove -y && \
apt-get -qq clean -y && \
rm -rf /var/lib/apt/lists/*

# Start with a clean slate on the mysql installation, as it
# may be mounted on a bland dir anyway
RUN rm -rf /var/lib/mysql/*

RUN chmod ugo+x /import.sh /healthcheck.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 3306 33060
CMD ["mysqld"]
HEALTHCHECK --interval=1s --retries=60 CMD ["/healthcheck.sh"]
