FROM bitnami/minideb

ENV MYSQL_DATABASE db
ENV MYSQL_USER db
ENV MYSQL_PASSWORD db
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_MAX_ALLOWED_PACKET 16m

RUN mkdir /docker-entrypoint-initdb.data
ADD files /

# Install mariadb non-interactive
ENV DEBIAN_FRONTEND="noninteractive"
RUN echo "mariadb-server mysql-server/root_password password $MYSQL_ROOT_PASSWORD" | debconf-set-selections && \
echo "mariadb-server mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD" | debconf-set-selections

RUN apt-get -qq update && \
apt-get -qq install software-properties-common dirmngr vim less wget sudo telnet && \
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8 && \
add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian stretch main' && \
apt-get -qq update && apt-get -qq install mariadb-server


RUN chmod ugo+x /import.sh /healthcheck.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 3306 33060
CMD ["mysqld"]
HEALTHCHECK --interval=1s --retries=60 CMD ["/healthcheck.sh"]
